export const HORSE_MAX_LEVEL = 30;

export interface IHorseStat {
    minLevel: number; // minimum player level required to have this horse level
    npcRace: number; // monster vnum for the horse NPC
    maxHealth: number; // max horse HP
    maxStamina: number; // max horse stamina
    st: number;
    dx: number;
    ht: number;
    iq: number;
    damMean: number;
    damMin: number;
    damMax: number;
    armor: number;
}

/**
 * Horse stat table indexed by horse level [0..HORSE_MAX_LEVEL].
 *
 * Grade 1 (Beginner):  levels  1-10 → npcRace 20101
 * Grade 2 (Intermediate): levels 11-20 → npcRace 20104
 * Grade 3 (Advanced):  levels 21-30 → npcRace 20107
 */
export const HORSE_STATS: IHorseStat[] = [
    // level 0 – no horse
    {
        minLevel: 0,
        npcRace: 0,
        maxHealth: 1,
        maxStamina: 1,
        st: 0,
        dx: 0,
        ht: 0,
        iq: 0,
        damMean: 0,
        damMin: 0,
        damMax: 0,
        armor: 0,
    },

    // Grade 1 – Beginner (levels 1-10)
    {
        minLevel: 25,
        npcRace: 20101,
        maxHealth: 3,
        maxStamina: 4,
        st: 26,
        dx: 35,
        ht: 18,
        iq: 9,
        damMean: 54,
        damMin: 43,
        damMax: 64,
        armor: 32,
    },
    {
        minLevel: 25,
        npcRace: 20101,
        maxHealth: 4,
        maxStamina: 4,
        st: 27,
        dx: 36,
        ht: 18,
        iq: 9,
        damMean: 55,
        damMin: 44,
        damMax: 66,
        armor: 33,
    },
    {
        minLevel: 25,
        npcRace: 20101,
        maxHealth: 5,
        maxStamina: 5,
        st: 28,
        dx: 38,
        ht: 19,
        iq: 9,
        damMean: 56,
        damMin: 44,
        damMax: 67,
        armor: 33,
    },
    {
        minLevel: 25,
        npcRace: 20101,
        maxHealth: 7,
        maxStamina: 5,
        st: 29,
        dx: 39,
        ht: 19,
        iq: 10,
        damMean: 57,
        damMin: 45,
        damMax: 68,
        armor: 34,
    },
    {
        minLevel: 25,
        npcRace: 20101,
        maxHealth: 8,
        maxStamina: 6,
        st: 30,
        dx: 40,
        ht: 20,
        iq: 10,
        damMean: 58,
        damMin: 46,
        damMax: 69,
        armor: 34,
    },
    {
        minLevel: 25,
        npcRace: 20101,
        maxHealth: 9,
        maxStamina: 6,
        st: 31,
        dx: 41,
        ht: 21,
        iq: 10,
        damMean: 59,
        damMin: 47,
        damMax: 70,
        armor: 35,
    },
    {
        minLevel: 25,
        npcRace: 20101,
        maxHealth: 11,
        maxStamina: 7,
        st: 32,
        dx: 42,
        ht: 21,
        iq: 11,
        damMean: 60,
        damMin: 48,
        damMax: 72,
        armor: 36,
    },
    {
        minLevel: 25,
        npcRace: 20101,
        maxHealth: 12,
        maxStamina: 7,
        st: 33,
        dx: 44,
        ht: 22,
        iq: 11,
        damMean: 61,
        damMin: 48,
        damMax: 73,
        armor: 36,
    },
    {
        minLevel: 25,
        npcRace: 20101,
        maxHealth: 13,
        maxStamina: 8,
        st: 34,
        dx: 45,
        ht: 22,
        iq: 11,
        damMean: 62,
        damMin: 49,
        damMax: 74,
        armor: 37,
    },
    {
        minLevel: 25,
        npcRace: 20101,
        maxHealth: 15,
        maxStamina: 10,
        st: 35,
        dx: 46,
        ht: 23,
        iq: 12,
        damMean: 63,
        damMin: 50,
        damMax: 75,
        armor: 37,
    },

    // Grade 2 – Intermediate (levels 11-20)
    {
        minLevel: 35,
        npcRace: 20104,
        maxHealth: 18,
        maxStamina: 30,
        st: 40,
        dx: 53,
        ht: 27,
        iq: 13,
        damMean: 69,
        damMin: 55,
        damMax: 82,
        armor: 41,
    },
    {
        minLevel: 35,
        npcRace: 20104,
        maxHealth: 19,
        maxStamina: 35,
        st: 41,
        dx: 54,
        ht: 27,
        iq: 14,
        damMean: 70,
        damMin: 56,
        damMax: 84,
        armor: 42,
    },
    {
        minLevel: 35,
        npcRace: 20104,
        maxHealth: 21,
        maxStamina: 40,
        st: 42,
        dx: 56,
        ht: 28,
        iq: 14,
        damMean: 71,
        damMin: 56,
        damMax: 85,
        armor: 42,
    },
    {
        minLevel: 35,
        npcRace: 20104,
        maxHealth: 22,
        maxStamina: 50,
        st: 43,
        dx: 57,
        ht: 28,
        iq: 14,
        damMean: 72,
        damMin: 57,
        damMax: 86,
        armor: 43,
    },
    {
        minLevel: 35,
        npcRace: 20104,
        maxHealth: 24,
        maxStamina: 55,
        st: 44,
        dx: 58,
        ht: 29,
        iq: 15,
        damMean: 73,
        damMin: 58,
        damMax: 87,
        armor: 43,
    },
    {
        minLevel: 35,
        npcRace: 20104,
        maxHealth: 25,
        maxStamina: 60,
        st: 44,
        dx: 59,
        ht: 30,
        iq: 15,
        damMean: 74,
        damMin: 59,
        damMax: 88,
        armor: 44,
    },
    {
        minLevel: 35,
        npcRace: 20104,
        maxHealth: 27,
        maxStamina: 65,
        st: 45,
        dx: 60,
        ht: 30,
        iq: 15,
        damMean: 75,
        damMin: 60,
        damMax: 90,
        armor: 45,
    },
    {
        minLevel: 35,
        npcRace: 20104,
        maxHealth: 28,
        maxStamina: 70,
        st: 46,
        dx: 62,
        ht: 31,
        iq: 15,
        damMean: 76,
        damMin: 60,
        damMax: 91,
        armor: 45,
    },
    {
        minLevel: 35,
        npcRace: 20104,
        maxHealth: 30,
        maxStamina: 80,
        st: 47,
        dx: 63,
        ht: 31,
        iq: 16,
        damMean: 77,
        damMin: 61,
        damMax: 92,
        armor: 46,
    },
    {
        minLevel: 35,
        npcRace: 20104,
        maxHealth: 32,
        maxStamina: 100,
        st: 48,
        dx: 64,
        ht: 32,
        iq: 16,
        damMean: 78,
        damMin: 62,
        damMax: 93,
        armor: 46,
    },

    // Grade 3 – Advanced (levels 21-30)
    {
        minLevel: 50,
        npcRace: 20107,
        maxHealth: 35,
        maxStamina: 120,
        st: 53,
        dx: 71,
        ht: 36,
        iq: 18,
        damMean: 84,
        damMin: 67,
        damMax: 100,
        armor: 50,
    },
    {
        minLevel: 50,
        npcRace: 20107,
        maxHealth: 36,
        maxStamina: 125,
        st: 55,
        dx: 74,
        ht: 37,
        iq: 18,
        damMean: 86,
        damMin: 68,
        damMax: 103,
        armor: 51,
    },
    {
        minLevel: 50,
        npcRace: 20107,
        maxHealth: 37,
        maxStamina: 130,
        st: 57,
        dx: 76,
        ht: 38,
        iq: 19,
        damMean: 88,
        damMin: 70,
        damMax: 105,
        armor: 52,
    },
    {
        minLevel: 50,
        npcRace: 20107,
        maxHealth: 38,
        maxStamina: 135,
        st: 59,
        dx: 78,
        ht: 39,
        iq: 20,
        damMean: 90,
        damMin: 72,
        damMax: 108,
        armor: 54,
    },
    {
        minLevel: 50,
        npcRace: 20107,
        maxHealth: 40,
        maxStamina: 140,
        st: 60,
        dx: 80,
        ht: 40,
        iq: 20,
        damMean: 91,
        damMin: 72,
        damMax: 109,
        armor: 54,
    },
    {
        minLevel: 50,
        npcRace: 20107,
        maxHealth: 42,
        maxStamina: 145,
        st: 61,
        dx: 81,
        ht: 40,
        iq: 20,
        damMean: 92,
        damMin: 73,
        damMax: 110,
        armor: 55,
    },
    {
        minLevel: 50,
        npcRace: 20107,
        maxHealth: 44,
        maxStamina: 150,
        st: 62,
        dx: 83,
        ht: 42,
        iq: 21,
        damMean: 94,
        damMin: 75,
        damMax: 112,
        armor: 56,
    },
    {
        minLevel: 50,
        npcRace: 20107,
        maxHealth: 46,
        maxStamina: 160,
        st: 63,
        dx: 84,
        ht: 42,
        iq: 21,
        damMean: 95,
        damMin: 76,
        damMax: 114,
        armor: 57,
    },
    {
        minLevel: 50,
        npcRace: 20107,
        maxHealth: 48,
        maxStamina: 170,
        st: 65,
        dx: 87,
        ht: 43,
        iq: 22,
        damMean: 97,
        damMin: 77,
        damMax: 116,
        armor: 58,
    },
    {
        minLevel: 50,
        npcRace: 20107,
        maxHealth: 50,
        maxStamina: 200,
        st: 67,
        dx: 89,
        ht: 45,
        iq: 22,
        damMean: 99,
        damMin: 79,
        damMax: 118,
        armor: 59,
    },
];

/**
 * Returns the grade (1–3) of a horse at the given level, or 0 if no horse.
 * Grade 1: levels  1-10
 * Grade 2: levels 11-20
 * Grade 3: levels 21-30
 */
export function getHorseGrade(level: number): number {
    if (level <= 0) return 0;
    return Math.floor((level - 1) / 10) + 1;
}

/**
 * Returns the NPC vnum (mount vnum sent to the client) for the given horse level.
 * Uses the base npcRace from the stats table.
 */
export function getHorseVnumByLevel(level: number): number {
    if (level <= 0 || level > HORSE_MAX_LEVEL) return 0;
    return HORSE_STATS[level].npcRace;
}
