export default {
    CHARACTER_SPAWNED: Symbol.for('CHARACTER_SPAWNED'),
    CHARACTER_INITIATED: Symbol.for('CHARACTER_INITIATED'),
    OTHER_CHARACTER_UPDATED: Symbol.for('OTHER_CHARACTER_UPDATED'),
    CHARACTER_MOVED: Symbol.for('CHARACTER_MOVED'),
    OTHER_CHARACTER_MOVED: Symbol.for('OTHER_CHARACTER_MOVED'),
};
