sonar.projectKey=willianmarquess_open-mt2
sonar.organization=willianmarquess

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**

sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6550
sonar.issue.ignore.multicriteria.e1.resourceKey=**/enum/**/*.ts
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S7767
sonar.issue.ignore.multicriteria.e2.resourceKey=**/enum/**/*.ts