sonar.projectKey=willianmarquess_open-mt2
sonar.organization=willianmarquess

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6550
sonar.issue.ignore.multicriteria.e1.resourceKey=**/enum/**/*.ts