//TODO: translate to english

export enum AffectBitsTypeEnum {
    NONE,
    YMIR,
    INVISIBILITY,
    SPAWN,
    POISON,
    SLOW,
    STUN,
    DUNGEON_READY,
    DUNGEON_UNIQUE,
    BUILDING_CONSTRUCTION_SMALL,
    BUILDING_CONSTRUCTION_LARGE,
    BUILDING_UPGRADE,
    MOV_SPEED_POTION,
    ATT_SPEED_POTION,
    FISH_MIND,
    BERSERK,
    AURA_OF_SWORD,
    STRONG_BODY,
    FEATHER_WALK,
    STEALTH,
    ENCHANTED_BLADE,
    TERROR,
    ENCHANTED_ARMOUR,
    BLESSING,
    REFLECT,
    SWIFTNESS,
    MANASHIELD,
    // AFF_MUYEONG (char_affect.h) - the toggle behind SKILL_MUYEONG/FlameSpiritSkill's orbiting
    // fireball; keep this ordinal (27) exactly where it is, it's the actual wire bit position.
    FLAME_SPIRIT,
    REVIVE_INVISIBLE,
    FIRE,
    DRAGON_AIDS,
    ATTACK_UP,
    TANHWAN_DASH,
    DISPEL,
    STRONG_BODY_WITH_FALL,
    POLYMORPH,
    WAR_FLAG1,
    WAR_FLAG2,
    WAR_FLAG3,
    CHINA_FIREWORK,
    HAIR,
    GERMANY,
    DRAGON_STRENGTH,
    LEADERSHIP,
}
