export enum ErrorTypesEnum {
    NAME_ALREADY_EXISTS = 1,
    ACCOUNT_FULL = 2,
    EMPIRE_NOT_SELECTED = 3,
    INVALID_TOKEN = 4,
    INVALID_USERNAME = 5,
    INVALID_PASSWORD = 6,
    EMPTY_ACCOUNT = 7,
    INVALID_EMPIRE = 8,
    PLAYER_NOT_FOUND = 9,
};
