export enum ItemAntiFlagEnum {
    ANTI_FEMALE = 1 << 0,
    ANTI_MALE = 1 << 1,
    ANTI_MUSA = 1 << 2,
    ANTI_ASSASSIN = 1 << 3,
    ANTI_SURA = 1 << 4,
    ANTI_MUDANG = 1 << 5,
    ANTI_GET = 1 << 6,
    ANTI_DROP = 1 << 7,
    ANTI_SELL = 1 << 8,
    ANTI_EMPIRE_A = 1 << 9,
    ANTI_EMPIRE_B = 1 << 10,
    ANTI_EMPIRE_C = 1 << 11,
    ANTI_SAVE = 1 << 12,
    ANTI_GIVE = 1 << 13,
    ANTI_PKDROP = 1 << 14,
    ANTI_STACK = 1 << 15,
    ANTI_MYSHOP = 1 << 16,
    ANTI_SAFEBOX = 1 << 17,
    ANTI_WOLFMAN = 1 << 18,
};
