export enum ItemSubTypeEnum {
    SWORD = 'WEAPON_SWORD',
    DAGGER = 'WEAPON_DAGGER',
    BOW = 'WEAPON_BOW',
    TWO_HANDED = 'WEAPON_TWO_HANDED',
    BELL = 'WEAPON_BELL',
    FAN = 'WEAPON_FAN',
    ARROW = 'WEAPON_ARROW',
    MOUNT_SPEAR = 'WEAPON_MOUNT_SPEAR',
    NUM_TYPES = 'WEAPON_NUM_TYPES',
}
