export default {
    ANTI_FEMALE: 0,
    ANTI_MALE: 1,
    ANTI_MUSA: 2,
    ANTI_ASSASSIN: 3,
    ANTI_SURA: 4,
    ANTI_MUDANG: 5,
    ANTI_GET: 6,
    ANTI_DROP: 7,
    ANTI_SELL: 8,
    ANTI_EMPIRE_A: 9,
    ANTI_EMPIRE_B: 10,
    ANTI_EMPIRE_C: 11,
    ANTI_SAVE: 12,
    ANTI_GIVE: 13,
    ANTI_PKDROP: 14,
    ANTI_STACK: 15,
    ANTI_MYSHOP: 16,
    ANTI_SAFEBOX: 17,
    ANTI_WOLFMAN: 18,
    NONE: -1,
};
