export enum ItemFlagEnum {
    ITEM_TUNABLE = 1 << 0,
    ITEM_SAVE = 1 << 1,
    ITEM_STACKABLE = 1 << 2,
    COUNT_PER_1GOLD = 1 << 3,
    ITEM_SLOW_QUERY = 1 << 4,
    ITEM_UNIQUE = 1 << 5,
    ITEM_MAKECOUNT = 1 << 6,
    ITEM_IRREMOVABLE = 1 << 7,
    CONFIRM_WHEN_USE = 1 << 8,
    QUEST_USE = 1 << 9,
    QUEST_USE_MULTIPLE = 1 << 10,
    QUEST_GIVE = 1 << 11,
    ITEM_QUEST = 1 << 12,
    LOG = 1 << 13,
    STACKABLE = 1 << 14,
    SLOW_QUERY = 1 << 15,
    REFINEABLE = 1 << 16,
    IRREMOVABLE = 1 << 17,
    ITEM_APPLICABLE = 1 << 18,
};
