export enum ItemResourceSubTypeEnum {
    RESOURCE_FISHBONE,
    RESOURCE_WATERSTONEPIECE,
    RESOURCE_WATERSTONE,
    RESOURCE_BLOOD_PEARL,
    RESOURCE_BLUE_PEARL,
    RESOURCE_WHITE_PEARL,
    RESOURCE_BUCKET,
    RESOURCE_CRYSTAL,
    RESOURCE_GEM,
    RESOURCE_STONE,
    RESOURCE_METIN,
    RESOURCE_ORE,
}
