export enum ItemMaterialSubTypeEnum {
    MATERIAL_LEATHER,
    MATERIAL_BLOOD,
    MATERIAL_ROOT,
    MATERIAL_NEEDLE,
    MATERIAL_JEWEL,
    MATERIAL_DS_REFINE_NORMAL,
    MATERIAL_DS_REFINE_BLESSED,
    MATERIAL_DS_REFINE_HOLLY,
}
