import { AffectBitsTypeEnum } from '@/core/enum/AffectBitsTypeEnum';

export enum SkillAffectEnum {
    YMIR,
    INVISIBILITY,
    SPAWN,
    POISON,
    SLOW,
    STUN,
    DUNGEON_READY,
    FORCE_VISIBLE,
    BUILDING_CONSTRUCTION_SMALL,
    BUILDING_CONSTRUCTION_LARGE,
    BUILDING_UPGRADE,
    MOV_SPEED_POTION,
    ATT_SPEED_POTION,
    FISH_MIND,
    BERSERK,
    AURA_OF_SWORD,
    STRONG_BODY,
    FEATHER_WALK,
    STEALTH,
    ENCHANTED_BLADE,
    TERROR,
    ENCHANTED_ARMOUR,
    BLESSING,
    REFLECT,
    SWIFTNESS,
    MANASHIELD,
    LEADERSHIP,
    REVIVE_INVISIBLE,
    FIRE,
    DRAGON_STRENGTH,
    ATTACK_UP,
    TANHWAN_DASH,
    FLAME_SPIRIT,
}

/**
 * Bridges the skill-data-facing SkillAffectEnum (declared on Skill.affects, not consumed at runtime
 * yet) to the actual runtime flag used by Character.isAffectByFlag/addAffect. Kept as an explicit
 * table (not a cast) since the two enums are declared independently - a typo in either one should
 * fail to compile here rather than silently resolve to the wrong flag.
 */
export const SKILL_AFFECT_TO_AFFECT_BITS_TYPE: Partial<Record<SkillAffectEnum, AffectBitsTypeEnum>> = {
    [SkillAffectEnum.YMIR]: AffectBitsTypeEnum.YMIR,
    [SkillAffectEnum.INVISIBILITY]: AffectBitsTypeEnum.INVISIBILITY,
    [SkillAffectEnum.SPAWN]: AffectBitsTypeEnum.SPAWN,
    [SkillAffectEnum.POISON]: AffectBitsTypeEnum.POISON,
    [SkillAffectEnum.SLOW]: AffectBitsTypeEnum.SLOW,
    [SkillAffectEnum.STUN]: AffectBitsTypeEnum.STUN,
    [SkillAffectEnum.DUNGEON_READY]: AffectBitsTypeEnum.DUNGEON_READY,
    [SkillAffectEnum.BUILDING_CONSTRUCTION_SMALL]: AffectBitsTypeEnum.BUILDING_CONSTRUCTION_SMALL,
    [SkillAffectEnum.BUILDING_CONSTRUCTION_LARGE]: AffectBitsTypeEnum.BUILDING_CONSTRUCTION_LARGE,
    [SkillAffectEnum.BUILDING_UPGRADE]: AffectBitsTypeEnum.BUILDING_UPGRADE,
    [SkillAffectEnum.MOV_SPEED_POTION]: AffectBitsTypeEnum.MOV_SPEED_POTION,
    [SkillAffectEnum.ATT_SPEED_POTION]: AffectBitsTypeEnum.ATT_SPEED_POTION,
    [SkillAffectEnum.FISH_MIND]: AffectBitsTypeEnum.FISH_MIND,
    [SkillAffectEnum.BERSERK]: AffectBitsTypeEnum.BERSERK,
    [SkillAffectEnum.AURA_OF_SWORD]: AffectBitsTypeEnum.AURA_OF_SWORD,
    [SkillAffectEnum.STRONG_BODY]: AffectBitsTypeEnum.STRONG_BODY,
    [SkillAffectEnum.FEATHER_WALK]: AffectBitsTypeEnum.FEATHER_WALK,
    [SkillAffectEnum.STEALTH]: AffectBitsTypeEnum.STEALTH,
    [SkillAffectEnum.ENCHANTED_BLADE]: AffectBitsTypeEnum.ENCHANTED_BLADE,
    [SkillAffectEnum.TERROR]: AffectBitsTypeEnum.TERROR,
    [SkillAffectEnum.ENCHANTED_ARMOUR]: AffectBitsTypeEnum.ENCHANTED_ARMOUR,
    [SkillAffectEnum.BLESSING]: AffectBitsTypeEnum.BLESSING,
    [SkillAffectEnum.REFLECT]: AffectBitsTypeEnum.REFLECT,
    [SkillAffectEnum.SWIFTNESS]: AffectBitsTypeEnum.SWIFTNESS,
    [SkillAffectEnum.MANASHIELD]: AffectBitsTypeEnum.MANASHIELD,
    [SkillAffectEnum.LEADERSHIP]: AffectBitsTypeEnum.LEADERSHIP,
    [SkillAffectEnum.REVIVE_INVISIBLE]: AffectBitsTypeEnum.REVIVE_INVISIBLE,
    [SkillAffectEnum.FIRE]: AffectBitsTypeEnum.FIRE,
    [SkillAffectEnum.DRAGON_STRENGTH]: AffectBitsTypeEnum.DRAGON_STRENGTH,
    [SkillAffectEnum.ATTACK_UP]: AffectBitsTypeEnum.ATTACK_UP,
    [SkillAffectEnum.TANHWAN_DASH]: AffectBitsTypeEnum.TANHWAN_DASH,
    [SkillAffectEnum.FLAME_SPIRIT]: AffectBitsTypeEnum.FLAME_SPIRIT,
    // No AffectBitsTypeEnum equivalent: FORCE_VISIBLE.
};
