export enum SkillEnum {
    SKILL_RESERVED = 0,

    // WARRIOR
    // BODY
    THREE_WAY_CUT = 1,
    SWORD_SPIN = 2,
    BERSERK = 3,
    AURA_OF_SWORD = 4,
    DASH = 5,

    // MENTAL
    SPIRIT_STRIKE = 16,
    BASH = 17,
    STUMP = 18,
    STRONG_BODY = 19,
    SWORD_STRIKE = 20,

    // ASSASIN
    // DAGGER
    AMBUSH = 31,
    FAST_ATTACK = 32,
    ROLLING_DAGGER = 33,
    STEALTH = 34,
    POISONOUS_CLOUD = 35,

    // ARCHER
    REPETITIVE_SHOT = 46,
    ARROW_SHOWER = 47,
    FIRE_ARROW = 48,
    FEATHER_WALK = 49,
    POISON_ARROW = 50,

    // SURA
    // WEAPON
    FINGER_STRIKE = 61,
    DRAGON_SWIRL = 62,
    ENCHANTED_BLADE = 63,
    FEAR = 64,
    ENCHANTED_ARMOUR = 65,
    DISPEL = 66,

    // MAGIC
    DARK_STRIKE = 76,
    FLAME_STRIKE = 77,
    FLAME_EXPLOSION = 78,
    DARK_PROTECTION = 79,
    SHOCKWAVE = 80,
    DARK_ORB = 81,

    // SHAMAN
    // BUFFER
    FLYING_TALISMAN = 91,
    SHOOTING_DRAGON = 92,
    DRAGON_ROAR = 93,
    //SKILL_BUDONG,
    BLESSING = 94,
    REFLECT = 95,
    DRAGON_STRENGTH = 96,

    // HEALER
    LIGHTNING_THROW = 106,
    SUMMON_LIGHTNING = 107,
    LIGHTNING_CLAW = 108,
    CURE = 109,
    SWIFTNESS = 110,
    ATTACK_UP = 111,

    SKILL_7_A_ANTI_DASH = 112,
    SKILL_7_B_ANTI_AMBUSH = 113,
    SKILL_7_C_ANTI_FINGER_STRIKE = 114,
    SKILL_7_D_ANTI_SHOOTING_DRAGON = 115,
    SKILL_8_A_ANTI_SPIRIT_STRIKE = 116,
    SKILL_8_B_ANTI_REPETITIVE_SHOT = 117,
    SKILL_8_C_ANTI_DISPEL = 118,
    SKILL_8_D_ANTI_SUMMON_LIGHTNING = 119,

    LEADERSHIP = 121,
    COMBO = 122,
    CREATE = 123,
    MINING = 124,

    LANGUAGE1 = 126,
    LANGUAGE2 = 127,
    LANGUAGE3 = 128,
    POLYMORPH = 129,

    HORSE = 130,
    HORSE_SUMMON = 131,
    HORSE_WILDATTACK = 137,
    HORSE_CHARGE = 138,
    HORSE_ESCAPE = 139,
    HORSE_WILDATTACK_RANGE = 140,

    ADD_HP = 141,
    RESIST_PENETRATE = 142,

    // GUILD_SKILL_START = 151,
    GUILD_SKILL_EYE = 151,
    GUILD_SKILL_BLOOD = 152,
    GUILD_SKILL_BLESS = 153,
    GUILD_SKILL_SEONGHWI = 154,
    GUILD_SKILL_ACCEL = 155,
    GUILD_SKILL_BUNNO = 156,
    GUILD_SKILL_JUMUN = 157,
    GUILD_SKILL_TELEPORT = 158,
    GUILD_SKILL_DOOR = 159,
    GUILD_SKILL_END = 162,
}
