export default {
    CHARACTER_SPAWNED: Symbol.for('CHARACTER_SPAWNED'),
    OTHER_CHARACTER_UPDATED: Symbol.for('OTHER_CHARACTER_UPDATED'),
    CHARACTER_MOVED: Symbol.for('CHARACTER_MOVED'),
    OTHER_CHARACTER_MOVED: Symbol.for('OTHER_CHARACTER_MOVED'),
    CHARACTER_POINTS_UPDATED: Symbol.for('CHARACTER_POINTS_UPDATED'),
    CHARACTER_LEVEL_UP: Symbol.for('CHARACTER_LEVEL_UP'),
    OTHER_CHARACTER_LEVEL_UP: Symbol.for('OTHER_CHARACTER_LEVEL_UP'),
    OTHER_CHARACTER_LEFT_GAME: Symbol.for('OTHER_CHARACTER_LEFT_GAME'),
    CHAT: Symbol.for('CHAT'),
    LOGOUT: Symbol.for('LOGOUT'),
    CHARACTER_TELEPORTED: Symbol.for('CHARACTER_TELEPORTED'),
};
